#server:
#  port: 8080
#  servlet:
#    context-path: /graduation

jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/graduation?useUnicode=true&charactorEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
  username: root
  password: graduation-mysql


#  mybatis
mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.chenlinghong.graduation.repository.domain


# REDIS (RedisProperties)
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # host: redis.xhunccd.top   # 域名备案成功后host修改为此项,需配置nginx
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: chenlinghong
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 10
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 20000

# 线程池配置
executor:
  core_pool_size: 5
  max_pool_size: 10
  queue_capacity: 1000
  thread_name_prefix: async-service-
  keep_alive_seconds: 5
